### ISSUE TITLE
M1 Formulate questions to ask client during M1 client meeting

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#1]
- Team member to formulate questions based on project description to be addressed during M1 meeting with the client for requirements gathering purposes

**Comment by Shadowtailx** [comment]
- Compiled questions to ask client during the M1 client meeting to facilitate the requirements gathering process.
- Compiled list of questions have been uploaded to the shared Google Drive for reference by the team.
- Task have been done before the deadline (i.e. meeting of client)
- 2/9/2023 - 3/9/2023
