### ISSUE TITLE
3.4.1 Non-functional Requirements - Performance Requirements for M1 report (Section 3)

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#10]
Task:
To come up with a list of Performance Requirements categorise under Non-function requirements

**Comment by Klovus** [comment]
- Added (non-functional requirements) Performance Requirements to 3.4.1
- Work has been committed
- Work completion is in line with project deadline
- No changes to the success or completion criteria of the task

08/09/2023 - 19/09/2023
