### ISSUE TITLE
2.1 Product Overview for M1 report (Section 2)

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#13]
- Describe the context and origin of the software
- Include a use case diagram that illustrates the major components of the overall system, subsystem interconnections, and external interface

**Comment by EltonOng** [comment]
Created system’s architecture diagram and described how our product works
Work done has been committed
Work done is in line with the project deadline
No changes to the success or completion criteria of the task
16/9/23 - 16/9/23
