### ISSUE TITLE
1.1 Product Scope for M1 report (Section 1)

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#14]
Included a short description of the software scope, boundaries and its purpose while including its benefits, objectives and goals.

**Comment by Dumbmes** [comment]
Update the M1 report with a short description of the software scope, boundaries and its purpose while including its benefits, objectives and goals.
Work done has been committed
Work done is in line with the project deadline
No changes to the success or completion criteria of the task
18/9/23 - 18/9/23
