### ISSUE TITLE
M2 Class Diagram: Crew

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#22]
Task ID : 2.1.2.1
Description: Creation of an overall class diagram
Goals: focusing on the Actor: Crew and its branches such as <<control>>
Success Criteria: Completion of the section by submission date 
Allocated Time: 25 Oct 2023 - 26 Oct 2023
Start Date: 25 Oct 2023
End Date: 26 Oct 2023
Owner: Jun Rui

**Comment by Klovus** [comment]
Creation of Crew Class for class diagram for review, inclusive of all related entity, control, and boundary.
- Work has been committed to shared Lucid chart link
- Work completion is in line with project deadline
- No changes to the success or completion criteria of the task


25/10/2023 - 26/10/2023
