### ISSUE TITLE
M3 Black-box Testing Decision Table and Reduce Table

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#24]
Task ID : 3.4
Description: Create Decision Table and Reduced Table for the black-box testing
Goals: To create Decision Table and create a Reduced Table for the test cases.
Success Criteria: To fully create the Decision Table and Reduced Table with Accuracy
Allocated Time: 07 Nov 2023
Start Date: 07 Nov 2023
End Date: 24 Nov 2023
Status: Completed
Priority: High
Owner: Zames Li

**Comment by Dumbmes** [comment]
Created the Decision Table and the Reduce Table and added to the report
Work has been committed
Work completion is in line with the project deadline
No changes to the success or completion criteria of the task.
19/11/2023 - 20/11/2023
