### ISSUE TITLE
3.3 Use Case Model/Diagram for M1 report (Section 3)

### ISSUE THREAD

**Issue by Klovus** [CRMNLS/INF-2001-Project#3]
List out the tasks or functions that the product is required to have

**Comment by Shadowtailx** [comment]
- Initial draft of the Use Case Diagram has been completed.
- A draft of the diagram has been uploaded to the shared Google Drive.
- Work done is in line with the completion deadline.
- To gather feedback with the team members and professors for further updates.
- 10/9/2023 - 10/9/2023

**Comment by Shadowtailx** [comment]
- Feedback of the initial draft has been gathered, and updated to the Use Case Diagram.
- Diagram has been uploaded to the shared Google Drive
- Work done is in line with the completion deadline.
- 16/9/2023 - 16/9/2023
