### ISSUE TITLE
1.3 Intended Audience and Document Overview for M1 report (Section 1)

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#31]
- List out the different types of reader that the project report is intended for. 
- Provide an overview of the document along with its intended flow

**Comment by Dumbmes** [comment]
Included the target audience as well as the overview of the document with the intended flow in the M1 report
Work done has been committed
Work done is in line with the project deadline
No changes to the success or completion criteria of the task
18/9/23 - 18/9/23
