### ISSUE TITLE
2.2 Product Functionality - Creation of Activity Diagram for M1 report (Section 2)

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#38]
Create an activity diagram to show one of the work process flow specifically showing when the crew member reject the job that was assigned to them

**Comment by EltonOng** [comment]
Added activity diagram to 2.2 Product Functionality
Work has been committed
Work completion is in line with project deadline
No changes to the success or completion criteria of the task
18/09/2023 - 22/09/2023
