### ISSUE TITLE
M2 Class Diagram: IT Manager

### ISSUE THREAD

**Issue by Klovus** [CRMNLS/INF-2001-Project#44]
Task:
Creation of an overall class diagram, focusing on the Actor: IT Manager and its branches such as <<control>>

**Comment by Shadowtailx** [comment]
- Created version 1 of IT Manager class for class diagram for review
- Work has been committed to shared Lucid chart link
- Work completion is in line with project deadline
- No changes to the success or completion criteria of the task
- 25/10/2023 - 26/10/2023
