### ISSUE TITLE
M1 Draft the first email to be sent to client

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#8]
Draft email to be sent to the client for review.
Ensure attachment of meeting minutes in the email.

**Comment by Shadowtailx** [comment]
- Emails have been drafted and reviewed by every team member.
- Email is ready to be sent out by the soft deadline set by the team.
- There are no changes to the success or completion criteria of the task.
- 09/09/2023 - 09/09/2023
