### ISSUE TITLE
3.2 Functional Requirements for M1 report (Section 3)

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#9]
- List out requirements that the product's interface should have
- Make use of screenshots of the wireframe to support the requirements listed

**Comment by Dumbmes** [comment]
Gathered all Functional requirements and listed in M1 report.
Work has been committed
Work completion is in line with project deadline
No changes to the success or completion criteria of the task
18/09/2023 - 22/09/2023
